### ISSUE TITLE
How to modify the CPU / MEM request of a deployed OCS/ODF?

### ISSUE THREAD

**Issue by TiloGit** [red-hat-storage/ocs-operator#2100]
How can we modify efficiently the `cpu` and `memory` request of the deployed ODF resources?
modify all deployments and sts? 
```yaml
        requests:
          cpu: '2'
          memory: 5Gi
```

Currently on my DEV cluster it request over 30 CPU request but as it's DEV usage is low. 
I would like to trim this. 

source seems here:  [controllers/defaults/resources.go](https://github.com/red-hat-storage/ocs-operator/blob/4eaa058368f079861cdf80bdc22a0f55d91dc676/controllers/defaults/resources.go#L14)

Thanks
