### ISSUE TITLE
Remove healthchecker cephclient from storageconsumer CR status

### ISSUE THREAD

**Issue by ezio-auditore** [red-hat-storage/ocs-operator#2829]
With the removal of the healthchecker cephclient from being created in https://github.com/red-hat-storage/ocs-operator/pull/2828 the same should be reflected in the StorageConsumer CR status as well.
```
cephResources:
  - kind: CephClient
    name: d2ee5d8373e686f9a69ec7add3360eff
    status: Ready
```
